/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedacteurProfilRouteImport } from './routes/redacteur.profil'
import { Route as RedacteurPaiementsRouteImport } from './routes/redacteur.paiements'
import { Route as RedacteurMissionsRouteImport } from './routes/redacteur.missions'
import { Route as RedacteurDashboardRouteImport } from './routes/redacteur.dashboard'
import { Route as EleveNouvelleCommandeRouteImport } from './routes/eleve.nouvelle-commande'
import { Route as EleveDashboardRouteImport } from './routes/eleve.dashboard'
import { Route as RedacteurMissionIdRouteImport } from './routes/redacteur.mission.$id'
import { Route as EleveCommandeIdRouteImport } from './routes/eleve.commande.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacteurProfilRoute = RedacteurProfilRouteImport.update({
  id: '/redacteur/profil',
  path: '/redacteur/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacteurPaiementsRoute = RedacteurPaiementsRouteImport.update({
  id: '/redacteur/paiements',
  path: '/redacteur/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacteurMissionsRoute = RedacteurMissionsRouteImport.update({
  id: '/redacteur/missions',
  path: '/redacteur/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacteurDashboardRoute = RedacteurDashboardRouteImport.update({
  id: '/redacteur/dashboard',
  path: '/redacteur/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EleveNouvelleCommandeRoute = EleveNouvelleCommandeRouteImport.update({
  id: '/eleve/nouvelle-commande',
  path: '/eleve/nouvelle-commande',
  getParentRoute: () => rootRouteImport,
} as any)
const EleveDashboardRoute = EleveDashboardRouteImport.update({
  id: '/eleve/dashboard',
  path: '/eleve/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacteurMissionIdRoute = RedacteurMissionIdRouteImport.update({
  id: '/redacteur/mission/$id',
  path: '/redacteur/mission/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EleveCommandeIdRoute = EleveCommandeIdRouteImport.update({
  id: '/eleve/commande/$id',
  path: '/eleve/commande/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/eleve/dashboard': typeof EleveDashboardRoute
  '/eleve/nouvelle-commande': typeof EleveNouvelleCommandeRoute
  '/redacteur/dashboard': typeof RedacteurDashboardRoute
  '/redacteur/missions': typeof RedacteurMissionsRoute
  '/redacteur/paiements': typeof RedacteurPaiementsRoute
  '/redacteur/profil': typeof RedacteurProfilRoute
  '/eleve/commande/$id': typeof EleveCommandeIdRoute
  '/redacteur/mission/$id': typeof RedacteurMissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/eleve/dashboard': typeof EleveDashboardRoute
  '/eleve/nouvelle-commande': typeof EleveNouvelleCommandeRoute
  '/redacteur/dashboard': typeof RedacteurDashboardRoute
  '/redacteur/missions': typeof RedacteurMissionsRoute
  '/redacteur/paiements': typeof RedacteurPaiementsRoute
  '/redacteur/profil': typeof RedacteurProfilRoute
  '/eleve/commande/$id': typeof EleveCommandeIdRoute
  '/redacteur/mission/$id': typeof RedacteurMissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/eleve/dashboard': typeof EleveDashboardRoute
  '/eleve/nouvelle-commande': typeof EleveNouvelleCommandeRoute
  '/redacteur/dashboard': typeof RedacteurDashboardRoute
  '/redacteur/missions': typeof RedacteurMissionsRoute
  '/redacteur/paiements': typeof RedacteurPaiementsRoute
  '/redacteur/profil': typeof RedacteurProfilRoute
  '/eleve/commande/$id': typeof EleveCommandeIdRoute
  '/redacteur/mission/$id': typeof RedacteurMissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/eleve/dashboard'
    | '/eleve/nouvelle-commande'
    | '/redacteur/dashboard'
    | '/redacteur/missions'
    | '/redacteur/paiements'
    | '/redacteur/profil'
    | '/eleve/commande/$id'
    | '/redacteur/mission/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/eleve/dashboard'
    | '/eleve/nouvelle-commande'
    | '/redacteur/dashboard'
    | '/redacteur/missions'
    | '/redacteur/paiements'
    | '/redacteur/profil'
    | '/eleve/commande/$id'
    | '/redacteur/mission/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/eleve/dashboard'
    | '/eleve/nouvelle-commande'
    | '/redacteur/dashboard'
    | '/redacteur/missions'
    | '/redacteur/paiements'
    | '/redacteur/profil'
    | '/eleve/commande/$id'
    | '/redacteur/mission/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EleveDashboardRoute: typeof EleveDashboardRoute
  EleveNouvelleCommandeRoute: typeof EleveNouvelleCommandeRoute
  RedacteurDashboardRoute: typeof RedacteurDashboardRoute
  RedacteurMissionsRoute: typeof RedacteurMissionsRoute
  RedacteurPaiementsRoute: typeof RedacteurPaiementsRoute
  RedacteurProfilRoute: typeof RedacteurProfilRoute
  EleveCommandeIdRoute: typeof EleveCommandeIdRoute
  RedacteurMissionIdRoute: typeof RedacteurMissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacteur/profil': {
      id: '/redacteur/profil'
      path: '/redacteur/profil'
      fullPath: '/redacteur/profil'
      preLoaderRoute: typeof RedacteurProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacteur/paiements': {
      id: '/redacteur/paiements'
      path: '/redacteur/paiements'
      fullPath: '/redacteur/paiements'
      preLoaderRoute: typeof RedacteurPaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacteur/missions': {
      id: '/redacteur/missions'
      path: '/redacteur/missions'
      fullPath: '/redacteur/missions'
      preLoaderRoute: typeof RedacteurMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacteur/dashboard': {
      id: '/redacteur/dashboard'
      path: '/redacteur/dashboard'
      fullPath: '/redacteur/dashboard'
      preLoaderRoute: typeof RedacteurDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleve/nouvelle-commande': {
      id: '/eleve/nouvelle-commande'
      path: '/eleve/nouvelle-commande'
      fullPath: '/eleve/nouvelle-commande'
      preLoaderRoute: typeof EleveNouvelleCommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleve/dashboard': {
      id: '/eleve/dashboard'
      path: '/eleve/dashboard'
      fullPath: '/eleve/dashboard'
      preLoaderRoute: typeof EleveDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacteur/mission/$id': {
      id: '/redacteur/mission/$id'
      path: '/redacteur/mission/$id'
      fullPath: '/redacteur/mission/$id'
      preLoaderRoute: typeof RedacteurMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleve/commande/$id': {
      id: '/eleve/commande/$id'
      path: '/eleve/commande/$id'
      fullPath: '/eleve/commande/$id'
      preLoaderRoute: typeof EleveCommandeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EleveDashboardRoute: EleveDashboardRoute,
  EleveNouvelleCommandeRoute: EleveNouvelleCommandeRoute,
  RedacteurDashboardRoute: RedacteurDashboardRoute,
  RedacteurMissionsRoute: RedacteurMissionsRoute,
  RedacteurPaiementsRoute: RedacteurPaiementsRoute,
  RedacteurProfilRoute: RedacteurProfilRoute,
  EleveCommandeIdRoute: EleveCommandeIdRoute,
  RedacteurMissionIdRoute: RedacteurMissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
